# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0002_auto_20180524_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
